/**
 * Forbidden Executor (🔴 Forbid)
 * Rejects changes to protected resources and high-risk changes
 * Generates a report instead of executing
 */

import { RiskLevel, EvolutionProposal, EvolutionResult } from '../types.js';
import { Executor } from './base.js';
import * as fs from 'fs';
import * as path from 'path';

export class ForbiddenExecutor implements Executor {
  private reportsDir: string;
  private logPath: string;

  constructor(dataDir: string) {
    this.reportsDir = path.join(dataDir, 'reports');
    this.logPath = path.join(dataDir, 'forbidden-attempts.log');
  }

  canHandle(level: RiskLevel): boolean {
    return level === 'forbid';
  }

  async execute(proposal: EvolutionProposal): Promise<EvolutionResult> {
    // Log the forbidden attempt
    await this.logForbiddenAttempt(proposal);

    // Generate a detailed report
    const reportFile = await this.generateReport(proposal);

    return {
      success: false,
      proposalId: proposal.id,
      action: 'forbidden',
      message: `🔴 Forbidden: ${proposal.target} is a protected resource or high-risk change.\nReport written to: ${reportFile}`,
      rollbackAvailable: false,
    };
  }

  // ============================================
  // Private methods
  // ============================================

  private async logForbiddenAttempt(proposal: EvolutionProposal): Promise<void> {
    const entry = {
      timestamp: new Date().toISOString(),
      proposalId: proposal.id,
      target: proposal.target,
      type: proposal.type,
      change: proposal.change,
      reasoning: proposal.reasoning,
      source: proposal.source,
    };

    const line = JSON.stringify(entry) + '\n';

    const dir = path.dirname(this.logPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.appendFileSync(this.logPath, line);
  }

  private async generateReport(proposal: EvolutionProposal): Promise<string> {
    // Ensure reports directory exists
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }

    const reportLines = [
      `# Forbidden Evolution Report`,
      ``,
      `## Summary`,
      `This evolution proposal was classified as 🔴 **forbidden** and was not executed.`,
      ``,
      `## Proposal Details`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| ID | ${proposal.id} |`,
      `| Type | ${proposal.type} |`,
      `| Target | ${proposal.target} |`,
      `| Generated | ${proposal.timestamp.toISOString()} |`,
      `| Source | ${proposal.source} |`,
      ``,
      `## Proposed Change`,
      '```',
      proposal.change,
      '```',
      ``,
      `## Reasoning`,
      proposal.reasoning,
      ``,
      `## Why This Was Forbidden`,
      ``,
    ];

    // Add reason based on target
    if (this.isProtectedPath(proposal.target)) {
      reportLines.push(`- Target is in a protected path (auth, secrets, etc.)`);
    }
    if (proposal.type === 'framework') {
      reportLines.push(`- Framework changes require manual review`);
    }
    if (proposal.change.toLowerCase().includes('delete')) {
      reportLines.push(`- Changes involving deletion are automatically forbidden`);
    }
    if (proposal.change.toLowerCase().includes('api') || proposal.change.toLowerCase().includes('key')) {
      reportLines.push(`- Changes involving API keys or secrets are forbidden`);
    }

    reportLines.push(
      ``,
      `## Recommendation`,
      `If you believe this change should be made, please:`,
      `1. Review the reasoning above`,
      `2. Manually apply the change if appropriate`,
      `3. Update the evolution configuration if needed`,
      ``,
      `---`,
      `*Generated by OpenClaw Evolution Plugin at ${new Date().toISOString()}*`
    );

    const report = reportLines.join('\n');
    const reportFile = path.join(this.reportsDir, `forbidden-${proposal.id}.md`);
    
    fs.writeFileSync(reportFile, report, 'utf-8');

    return reportFile;
  }

  private isProtectedPath(target: string): boolean {
    const protectedPatterns = [
      /\/auth\//,
      /\/secrets\//,
      /\.env$/,
      /key/i,
      /secret/i,
      /password/i,
      /token/i,
    ];

    return protectedPatterns.some(pattern => pattern.test(target));
  }
}
