/**
 * Suggest Executor (L2)
 * Generates a report with suggestions without making changes
 */

import { RiskLevel, EvolutionProposal, EvolutionResult } from '../types.js';
import { Executor } from './base.js';
import * as fs from 'fs';
import * as path from 'path';

export class SuggestExecutor implements Executor {
  private reportsDir: string;

  constructor(dataDir: string) {
    this.reportsDir = path.join(dataDir, 'reports');
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  canHandle(level: RiskLevel): boolean {
    return level === 'L2';
  }

  async execute(proposal: EvolutionProposal): Promise<EvolutionResult> {
    try {
      // Generate a detailed report
      const report = this.generateReport(proposal);

      // Save the report
      const reportPath = await this.saveReport(proposal, report);

      return {
        success: true,
        proposalId: proposal.id,
        action: 'suggested',
        message: `Generated suggestion report: ${reportPath}`,
        rollbackAvailable: false,
      };
    } catch (error) {
      return {
        success: false,
        proposalId: proposal.id,
        action: 'suggested',
        message: `Failed to generate report: ${error instanceof Error ? error.message : 'Unknown error'}`,
        rollbackAvailable: false,
      };
    }
  }

  // ============================================
  // Private methods
  // ============================================

  private generateReport(proposal: EvolutionProposal): string {
    return `
# Evolution Suggestion Report

**Generated:** ${new Date().toISOString()}
**Proposal ID:** ${proposal.id}
**Risk Level:** L2 (Suggestion Only)

## Target
- **Type:** ${proposal.type}
- **Path:** ${proposal.target}

## Proposed Change
${proposal.change}

## Reasoning
${proposal.reasoning}

## Why This is L2
This change is classified as L2 (Suggestion Only) because it involves significant
modifications that could have broad impact. Manual review and approval is required.

## Recommendations

### Before Making This Change
1. Backup current state
2. Review the target file/function
3. Consider alternative approaches
4. Plan for rollback if needed

### Implementation Steps
1. Review the proposed change carefully
2. Test in a development environment if possible
3. Document the change and reasoning
4. Monitor for unexpected effects

## Manual Action Required
To apply this change, you need to:
1. Review the suggestion above
2. Manually edit the target: \`${proposal.target}\`
3. Or downgrade to L1 if appropriate with proper safeguards

---
*This report was generated by OpenClaw Evolution Plugin*
`;
  }

  private async saveReport(proposal: EvolutionProposal, report: string): Promise<string> {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `suggestion-${proposal.id}-${timestamp}.md`;
    const reportPath = path.join(this.reportsDir, filename);

    fs.writeFileSync(reportPath, report);

    return reportPath;
  }
}
